### ISSUE TITLE
Edge fails the current tests

### ISSUE THREAD

**Issue by mzgol** [jquery/sizzle#347]
See https://travis-ci.org/jquery/sizzle/builds/75967778; an example build where I added Edge testing. One error is #339 but there are others:

```
Edge 12.0.0 (Windows 10 0.0.0) selector matchesSelector FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1252:1): Permission denied
	
	Expected 16 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1252:1)
	
Edge 12.0.0 (Windows 10 0.0.0) selector matches FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1292:1): Permission denied
	
	Expected 4 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1292:1)
	
Edge 12.0.0 (Windows 10 0.0.0) selector select() with pre-compiled function FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1319:1): Permission denied
	
	Expected 6 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/selector.js:1319:1)
	
Edge 12.0.0 (Windows 10 0.0.0) utilities Sizzle.attr (HTML) FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:39:1): Permission denied
	
	Expected 9 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:39:1)
	
Edge 12.0.0 (Windows 10 0.0.0) utilities Sizzle.attr (XML) FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:43:1): Permission denied
	
	Expected 9 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:43:1)
	
Edge 12.0.0 (Windows 10 0.0.0) utilities Sizzle.contains FAILED
	Died on test #4    at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:47:1): Permission denied
	
	Expected 16 assertions, but 4 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:47:1)
	
Edge 12.0.0 (Windows 10 0.0.0) utilities Sizzle.contains in SVG (jQuery #10832) FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:74:2): Permission denied
	
	Expected 4 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:74:2)
	
Edge 12.0.0 (Windows 10 0.0.0) utilities Sizzle.uniqueSort FAILED
	Died on test #9    at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:90:1): Permission denied
	
	Expected 14 assertions, but 9 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/utilities.js:90:1)
	
..
Edge 12.0.0 (Windows 10 0.0.0) extending custom pseudos FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:3:1): Permission denied
	
	Expected 6 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:3:1)
	
Edge 12.0.0 (Windows 10 0.0.0) extending backwards-compatible custom pseudos FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:59:1): Permission denied
	
	Expected 3 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:59:1)
	
Edge 12.0.0 (Windows 10 0.0.0) extending custom attribute getters FAILED
	Died on test #1    at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:79:1): Permission denied
	
	Expected 2 assertions, but 1 were run
	   at Global code (/home/travis/build/jquery/sizzle/test/unit/extending.js:79:1)
```

**Comment by mzgol** [comment]
Ah, it might be related to #339 after all. This one failure may screw up later tests...

**Comment by mzgol** [comment]
I'll close it for now unless it turns out the failures are legitimate.
